var test_order = [
       {
           "invoice_number": "30967",
           "patient_id_cp": "7378",
           "patient_id_wc": "5315",
           "count_items": "1",
           "count_filled": 1,
           "count_nofill": null,
           "order_source": null,
           "order_stage_cp": "Entered",
           "order_stage_wc": "prepare-erx",
           "order_status": "Surescripts Fill",
           "invoice_doc_id": null,
           "order_address1": "1780 Corporate Dr",
           "order_address2": "Suite 100",
           "order_city": "Norcross",
           "order_state": "GA",
           "order_zip": "30093",
           "tracking_number": null,
           "order_date_added": "2020-03-27 10:39:27",
           "order_date_changed": "2020-03-27 10:39:27",
           "order_date_updated": "2020-03-27 14:40:31",
           "order_date_dispensed": null,
           "order_date_shipped": null,
           "order_date_returned": null,
           "payment_total_default": null,
           "payment_total_actual": null,
           "payment_fee_default": null,
           "payment_fee_actual": null,
           "payment_due_default": null,
           "payment_due_actual": null,
           "payment_date_autopay": null,
           "payment_method_actual": null,
           "coupon_lines": null,
           "order_note": null,
           "first_name": "FIRSTNAME",
           "last_name": "LASTNAME",
           "birth_date": "1985-03-10",
           "patient_note": "",
           "phone1": "1234567890",
           "phone2": null,
           "email": "april.britt@wellstar.org",
           "patient_autofill": "1",
           "pharmacy_name": "Wellstar Pharmacy Network",
           "pharmacy_npi": "1437458171",
           "pharmacy_fax": "7707939945",
           "pharmacy_phone": "7707939300",
           "pharmacy_address": "677 Church St Ne",
           "payment_card_type": null,
           "payment_card_last4": null,
           "payment_card_date_expired": null,
           "payment_method_default": "cheque",
           "payment_coupon": null,
           "tracking_coupon": null,
           "patient_address1": "1780 Corporate Dr",
           "patient_address2": "Suite 100",
           "patient_city": "Norcross",
           "patient_state": "GA",
           "patient_zip": "30093",
           "refills_used": "2.57",
           "patient_status": "1",
           "language": "EN",
           "allergies_none": null,
           "allergies_cephalosporins": null,
           "allergies_sulfa": null,
           "allergies_aspirin": null,
           "allergies_penicillin": null,
           "allergies_erythromycin": null,
           "allergies_codeine": null,
           "allergies_nsaids": null,
           "allergies_salicylates": null,
           "allergies_azithromycin": null,
           "allergies_amoxicillin": null,
           "allergies_tetracycline": null,
           "allergies_other": "Iodine",
           "medications_other": null,
           "patient_date_added": "2020-03-10 10:17:01",
           "patient_date_changed": "2020-03-10 00:00:00",
           "patient_date_updated": "2020-03-16 04:01:56",
           "drug_generic": "Tamsulosin 0.4mg",
           "drug_brand": null,
           "drug_name": "TAMSULOSIN 0.4MG CAP",
           "sig_qty_per_day": "0.033",
           "max_gsn": "27546",
           "drug_gsns": ",27546,",
           "refills_total": "1.00",
           "rx_autofill": "1",
           "refill_date_first": null,
           "refill_date_last": null,
           "refill_date_next": null,
           "refill_date_manual": null,
           "refill_date_default": null,
           "best_rx_number": "6027756",
           "rx_numbers": ",6027756,",
           "rx_sources": "SureScripts",
           "rx_date_changed": "2020-03-27 10:39:27",
           "rx_date_expired": "2021-03-27",
           "rx_date_transferred": null,
           "rx_number": "6027756",
           "rx_dispensed_id": null,
           "group": null,
           "stock_level_initial": "HIGH SUPPLY",
           "refills_dispensed_default": 0,
           "refills_dispensed_actual": null,
           "days_dispensed_default": 90,
           "days_dispensed_actual": null,
           "qty_dispensed_default": 2.97,
           "qty_dispensed_actual": null,
           "price_dispensed_default": 6,
           "price_dispensed_actual": null,
           "qty_pended_total": null,
           "qty_pended_repacks": null,
           "count_pended_total": null,
           "count_pended_repacks": null,
           "item_message_key": "NO ACTION STANDARD FILL",
           "item_message_text": "",
           "item_type": null,
           "item_added_by": "HL7",
           "item_date_added": "2020-03-27 10:39:27",
           "refill_target_date": null,
           "refill_target_days": null,
           "refill_target_rxs": null,
           "rx_gsn": "27546",
           "days_left": "365",
           "refills_left": "1.00",
           "refills_original": "1.00",
           "qty_left": "30.000",
           "qty_original": "30.000",
           "sig_actual": "Take 1 capsule (0.4 mg total) by mouth nightly",
           "sig_initial": "Take 1 capsule (0.4 mg total) by mouth nightly",
           "sig_clean": "Take 1 capsule by mouth nightly",
           "sig_qty": "2.000",
           "sig_days": "60",
           "sig_durations": ",0,",
           "sig_qtys_per_time": ",1,",
           "sig_frequencies": ",1,",
           "sig_frequency_numerators": ",1,",
           "sig_frequency_denominators": ",1,",
           "rx_status": "0",
           "rx_stage": "SureScripts",
           "rx_source": "SureScripts",
           "rx_transfer": null,
           "provider_npi": "1689987430",
           "provider_first_name": "Mitra",
           "provider_last_name": "Moshksaran",
           "provider_clinic": "",
           "provider_phone": "4707930200",
           "message_display": null,
           "stock_level": "HIGH SUPPLY",
           "price_per_month": "2.00",
           "drug_ordered": "1",
           "qty_repack": "135",
           "qty_inventory": "9961.7",
           "qty_entered": "27101.0",
           "qty_dispensed": 2.97,
           "stock_threshold": "4.0",
           "drug": "TAMSULOSIN 0.4MG CAP",
           "days_dispensed": 90,
           "payment_method": "cheque",
           "refills_dispensed": 1,
           "price_dispensed": 6
       },
       {
           "invoice_number": "30967",
           "patient_id_cp": "7378",
           "patient_id_wc": "5315",
           "count_items": "1",
           "count_filled": 1,
           "count_nofill": null,
           "order_source": null,
           "order_stage_cp": "Entered",
           "order_stage_wc": "prepare-erx",
           "order_status": "Surescripts Fill",
           "invoice_doc_id": null,
           "order_address1": "1780 Corporate Dr",
           "order_address2": "Suite 100",
           "order_city": "Norcross",
           "order_state": "GA",
           "order_zip": "30093",
           "tracking_number": null,
           "order_date_added": "2020-03-27 10:39:27",
           "order_date_changed": "2020-03-27 10:39:27",
           "order_date_updated": "2020-03-27 14:40:31",
           "order_date_dispensed": null,
           "order_date_shipped": null,
           "order_date_returned": null,
           "payment_total_default": null,
           "payment_total_actual": null,
           "payment_fee_default": null,
           "payment_fee_actual": null,
           "payment_due_default": null,
           "payment_due_actual": null,
           "payment_date_autopay": null,
           "payment_method_actual": null,
           "coupon_lines": null,
           "order_note": null,
           "first_name": "FIRSTNAME",
           "last_name": "LASTNAME",
           "birth_date": "1985-03-10",
           "patient_note": "",
           "phone1": "1234567890",
           "phone2": null,
           "email": "april.britt@wellstar.org",
           "patient_autofill": "1",
           "pharmacy_name": "Wellstar Pharmacy Network",
           "pharmacy_npi": "1437458171",
           "pharmacy_fax": "7707939945",
           "pharmacy_phone": "7707939300",
           "pharmacy_address": "677 Church St Ne",
           "payment_card_type": null,
           "payment_card_last4": null,
           "payment_card_date_expired": null,
           "payment_method_default": "cheque",
           "payment_coupon": null,
           "tracking_coupon": null,
           "patient_address1": "1780 Corporate Dr",
           "patient_address2": "Suite 100",
           "patient_city": "Norcross",
           "patient_state": "GA",
           "patient_zip": "30093",
           "refills_used": "2.57",
           "patient_status": "1",
           "language": "EN",
           "allergies_none": null,
           "allergies_cephalosporins": null,
           "allergies_sulfa": null,
           "allergies_aspirin": null,
           "allergies_penicillin": null,
           "allergies_erythromycin": null,
           "allergies_codeine": null,
           "allergies_nsaids": null,
           "allergies_salicylates": null,
           "allergies_azithromycin": null,
           "allergies_amoxicillin": null,
           "allergies_tetracycline": null,
           "allergies_other": "Iodine",
           "medications_other": null,
           "patient_date_added": "2020-03-10 10:17:01",
           "patient_date_changed": "2020-03-10 00:00:00",
           "patient_date_updated": "2020-03-16 04:01:56",
           "drug_generic": "Metoprolol Succinate 25mg Er",
           "drug_brand": "Toprol Xl",
           "drug_name": "METOPROLOL SUCC ER 25MG TAB",
           "sig_qty_per_day": "2.000",
           "max_gsn": "47586",
           "drug_gsns": ",47586,",
           "refills_total": "3.00",
           "rx_autofill": "1",
           "refill_date_first": null,
           "refill_date_last": null,
           "refill_date_next": null,
           "refill_date_manual": null,
           "refill_date_default": null,
           "best_rx_number": "6026808",
           "rx_numbers": ",6026808,",
           "rx_sources": "SureScripts",
           "rx_date_changed": "2020-03-10 10:22:04",
           "rx_date_expired": "2021-03-10",
           "rx_date_transferred": null,
           "rx_number": null,
           "rx_dispensed_id": null,
           "group": null,
           "stock_level_initial": null,
           "refills_dispensed_default": null,
           "refills_dispensed_actual": null,
           "days_dispensed_default": null,
           "days_dispensed_actual": null,
           "qty_dispensed_default": null,
           "qty_dispensed_actual": null,
           "price_dispensed_default": null,
           "price_dispensed_actual": null,
           "qty_pended_total": null,
           "qty_pended_repacks": null,
           "count_pended_total": null,
           "count_pended_repacks": null,
           "item_message_key": "NO ACTION NEW RX SYNCED TO ORDER",
           "item_message_text": "is a new Rx synced to Order **",
           "item_type": null,
           "item_added_by": null,
           "item_date_added": null,
           "refill_target_date": null,
           "refill_target_days": null,
           "refill_target_rxs": null,
           "rx_gsn": null,
           "days_left": null,
           "refills_left": null,
           "refills_original": null,
           "qty_left": null,
           "qty_original": null,
           "sig_actual": null,
           "sig_initial": null,
           "sig_clean": null,
           "sig_qty": null,
           "sig_days": null,
           "sig_durations": null,
           "sig_qtys_per_time": null,
           "sig_frequencies": null,
           "sig_frequency_numerators": null,
           "sig_frequency_denominators": null,
           "rx_status": null,
           "rx_stage": null,
           "rx_source": null,
           "rx_transfer": null,
           "provider_npi": null,
           "provider_first_name": null,
           "provider_last_name": null,
           "provider_clinic": null,
           "provider_phone": null,
           "message_display": null,
           "stock_level": "HIGH SUPPLY",
           "price_per_month": "2.00",
           "drug_ordered": "1",
           "qty_repack": "135",
           "qty_inventory": "8206.0",
           "qty_entered": "14395.0",
           "qty_dispensed": 0,
           "stock_threshold": "1.6",
           "drug": "METOPROLOL SUCC ER 25MG TAB",
           "days_dispensed": null,
           "payment_method": "cheque",
           "refills_dispensed": 3,
           "price_dispensed": 0
       },
       {
           "invoice_number": "30967",
           "patient_id_cp": "7378",
           "patient_id_wc": "5315",
           "count_items": "1",
           "count_filled": 1,
           "count_nofill": null,
           "order_source": null,
           "order_stage_cp": "Entered",
           "order_stage_wc": "prepare-erx",
           "order_status": "Surescripts Fill",
           "invoice_doc_id": null,
           "order_address1": "1780 Corporate Dr",
           "order_address2": "Suite 100",
           "order_city": "Norcross",
           "order_state": "GA",
           "order_zip": "30093",
           "tracking_number": null,
           "order_date_added": "2020-03-27 10:39:27",
           "order_date_changed": "2020-03-27 10:39:27",
           "order_date_updated": "2020-03-27 14:40:31",
           "order_date_dispensed": null,
           "order_date_shipped": null,
           "order_date_returned": null,
           "payment_total_default": null,
           "payment_total_actual": null,
           "payment_fee_default": null,
           "payment_fee_actual": null,
           "payment_due_default": null,
           "payment_due_actual": null,
           "payment_date_autopay": null,
           "payment_method_actual": null,
           "coupon_lines": null,
           "order_note": null,
           "first_name": "FIRSTNAME",
           "last_name": "LASTNAME",
           "birth_date": "1985-03-10",
           "patient_note": "",
           "phone1": "1234567890",
           "phone2": null,
           "email": "april.britt@wellstar.org",
           "patient_autofill": "1",
           "pharmacy_name": "Wellstar Pharmacy Network",
           "pharmacy_npi": "1437458171",
           "pharmacy_fax": "7707939945",
           "pharmacy_phone": "7707939300",
           "pharmacy_address": "677 Church St Ne",
           "payment_card_type": null,
           "payment_card_last4": null,
           "payment_card_date_expired": null,
           "payment_method_default": "cheque",
           "payment_coupon": null,
           "tracking_coupon": null,
           "patient_address1": "1780 Corporate Dr",
           "patient_address2": "Suite 100",
           "patient_city": "Norcross",
           "patient_state": "GA",
           "patient_zip": "30093",
           "refills_used": "2.57",
           "patient_status": "1",
           "language": "EN",
           "allergies_none": null,
           "allergies_cephalosporins": null,
           "allergies_sulfa": null,
           "allergies_aspirin": null,
           "allergies_penicillin": null,
           "allergies_erythromycin": null,
           "allergies_codeine": null,
           "allergies_nsaids": null,
           "allergies_salicylates": null,
           "allergies_azithromycin": null,
           "allergies_amoxicillin": null,
           "allergies_tetracycline": null,
           "allergies_other": "Iodine",
           "medications_other": null,
           "patient_date_added": "2020-03-10 10:17:01",
           "patient_date_changed": "2020-03-10 00:00:00",
           "patient_date_updated": "2020-03-16 04:01:56",
           "drug_generic": "Metoprolol Succinate 25mg Er",
           "drug_brand": "Toprol Xl",
           "drug_name": "METOPROLOL SUCC ER 25MG TAB",
           "sig_qty_per_day": "4.000",
           "max_gsn": "47586",
           "drug_gsns": ",47586,",
           "refills_total": "0.33",
           "rx_autofill": "1",
           "refill_date_first": "2020-03-12",
           "refill_date_last": "2020-03-12",
           "refill_date_next": "2020-06-10",
           "refill_date_manual": null,
           "refill_date_default": "2020-06-10",
           "best_rx_number": "6026805",
           "rx_numbers": ",6026805,",
           "rx_sources": "Refill",
           "rx_date_changed": "2020-03-12 11:36:58",
           "rx_date_expired": "2021-03-10",
           "rx_date_transferred": null,
           "rx_number": null,
           "rx_dispensed_id": null,
           "group": null,
           "stock_level_initial": null,
           "refills_dispensed_default": null,
           "refills_dispensed_actual": null,
           "days_dispensed_default": null,
           "days_dispensed_actual": null,
           "qty_dispensed_default": null,
           "qty_dispensed_actual": null,
           "price_dispensed_default": null,
           "price_dispensed_actual": null,
           "qty_pended_total": null,
           "qty_pended_repacks": null,
           "count_pended_total": null,
           "count_pended_repacks": null,
           "item_message_key": "NO ACTION NOT DUE",
           "item_message_text": "is not due until 2020-06-10 **",
           "item_type": null,
           "item_added_by": null,
           "item_date_added": null,
           "refill_target_date": null,
           "refill_target_days": null,
           "refill_target_rxs": null,
           "rx_gsn": null,
           "days_left": null,
           "refills_left": null,
           "refills_original": null,
           "qty_left": null,
           "qty_original": null,
           "sig_actual": null,
           "sig_initial": null,
           "sig_clean": null,
           "sig_qty": null,
           "sig_days": null,
           "sig_durations": null,
           "sig_qtys_per_time": null,
           "sig_frequencies": null,
           "sig_frequency_numerators": null,
           "sig_frequency_denominators": null,
           "rx_status": null,
           "rx_stage": null,
           "rx_source": null,
           "rx_transfer": null,
           "provider_npi": null,
           "provider_first_name": null,
           "provider_last_name": null,
           "provider_clinic": null,
           "provider_phone": null,
           "message_display": null,
           "stock_level": "HIGH SUPPLY",
           "price_per_month": "2.00",
           "drug_ordered": "1",
           "qty_repack": "135",
           "qty_inventory": "8206.0",
           "qty_entered": "14395.0",
           "qty_dispensed": 0,
           "stock_threshold": "1.6",
           "drug": "METOPROLOL SUCC ER 25MG TAB (4 per day)",
           "days_dispensed": null,
           "payment_method": "cheque",
           "refills_dispensed": 0.33,
           "price_dispensed": 0
       },
       {
           "invoice_number": "30967",
           "patient_id_cp": "7378",
           "patient_id_wc": "5315",
           "count_items": "1",
           "count_filled": 1,
           "count_nofill": null,
           "order_source": null,
           "order_stage_cp": "Entered",
           "order_stage_wc": null,
           "order_status": "Surescripts Fill",
           "invoice_doc_id": null,
           "order_address1": "1780 Corporate Dr",
           "order_address2": "Suite 100",
           "order_city": "Norcross",
           "order_state": "GA",
           "order_zip": "30093",
           "tracking_number": null,
           "order_date_added": "2020-03-27 10:39:27",
           "order_date_changed": "2020-03-27 10:39:27",
           "order_date_updated": "2020-03-27 14:40:31",
           "order_date_dispensed": null,
           "order_date_shipped": null,
           "order_date_returned": null,
           "payment_total_default": null,
           "payment_total_actual": null,
           "payment_fee_default": null,
           "payment_fee_actual": null,
           "payment_due_default": null,
           "payment_due_actual": null,
           "payment_date_autopay": null,
           "payment_method_actual": null,
           "coupon_lines": null,
           "order_note": null,
           "first_name": "FIRSTNAME",
           "last_name": "LASTNAME",
           "birth_date": "1985-03-10",
           "patient_note": "",
           "phone1": "1234567890",
           "phone2": null,
           "email": "april.britt@wellstar.org",
           "patient_autofill": "1",
           "pharmacy_name": "Wellstar Pharmacy Network",
           "pharmacy_npi": "1437458171",
           "pharmacy_fax": "7707939945",
           "pharmacy_phone": "7707939300",
           "pharmacy_address": "677 Church St Ne",
           "payment_card_type": null,
           "payment_card_last4": null,
           "payment_card_date_expired": null,
           "payment_method_default": "cheque",
           "payment_coupon": null,
           "tracking_coupon": null,
           "patient_address1": "1780 Corporate Dr",
           "patient_address2": "Suite 100",
           "patient_city": "Norcross",
           "patient_state": "GA",
           "patient_zip": "30093",
           "refills_used": "2.57",
           "patient_status": "1",
           "language": "EN",
           "allergies_none": null,
           "allergies_cephalosporins": null,
           "allergies_sulfa": null,
           "allergies_aspirin": null,
           "allergies_penicillin": null,
           "allergies_erythromycin": null,
           "allergies_codeine": null,
           "allergies_nsaids": null,
           "allergies_salicylates": null,
           "allergies_azithromycin": null,
           "allergies_amoxicillin": null,
           "allergies_tetracycline": null,
           "allergies_other": "Iodine",
           "medications_other": null,
           "patient_date_added": "2020-03-10 10:17:01",
           "patient_date_changed": "2020-03-10 00:00:00",
           "patient_date_updated": "2020-03-16 04:01:56",
           "drug_generic": "Spironolactone 25mg",
           "drug_brand": "Aldactone",
           "drug_name": "SPIRONOLACTONE 25MG TAB",
           "sig_qty_per_day": "1.000",
           "max_gsn": "6817",
           "drug_gsns": ",6817,",
           "refills_total": "6.00",
           "rx_autofill": "1",
           "refill_date_first": "2020-03-12",
           "refill_date_last": "2020-03-12",
           "refill_date_next": "2020-06-10",
           "refill_date_manual": null,
           "refill_date_default": "2020-06-10",
           "best_rx_number": "6026807",
           "rx_numbers": ",6026807,",
           "rx_sources": "Refill",
           "rx_date_changed": "2020-03-12 11:37:28",
           "rx_date_expired": "2021-03-10",
           "rx_date_transferred": null,
           "rx_number": null,
           "rx_dispensed_id": null,
           "group": null,
           "stock_level_initial": null,
           "refills_dispensed_default": null,
           "refills_dispensed_actual": null,
           "days_dispensed_default": null,
           "days_dispensed_actual": null,
           "qty_dispensed_default": null,
           "qty_dispensed_actual": null,
           "price_dispensed_default": null,
           "price_dispensed_actual": null,
           "qty_pended_total": null,
           "qty_pended_repacks": null,
           "count_pended_total": null,
           "count_pended_repacks": null,
           "item_message_key": "NO ACTION NOT DUE",
           "item_message_text": "is not due until 2020-06-10 **",
           "item_type": null,
           "item_added_by": null,
           "item_date_added": null,
           "refill_target_date": null,
           "refill_target_days": null,
           "refill_target_rxs": null,
           "rx_gsn": null,
           "days_left": null,
           "refills_left": null,
           "refills_original": null,
           "qty_left": null,
           "qty_original": null,
           "sig_actual": null,
           "sig_initial": null,
           "sig_clean": null,
           "sig_qty": null,
           "sig_days": null,
           "sig_durations": null,
           "sig_qtys_per_time": null,
           "sig_frequencies": null,
           "sig_frequency_numerators": null,
           "sig_frequency_denominators": null,
           "rx_status": null,
           "rx_stage": null,
           "rx_source": null,
           "rx_transfer": null,
           "provider_npi": null,
           "provider_first_name": null,
           "provider_last_name": null,
           "provider_clinic": null,
           "provider_phone": null,
           "message_display": null,
           "stock_level": "HIGH SUPPLY",
           "price_per_month": "2.00",
           "drug_ordered": "1",
           "qty_repack": "135",
           "qty_inventory": "8093.7",
           "qty_entered": "12506.0",
           "qty_dispensed": 0,
           "stock_threshold": "1.3",
           "drug": "SPIRONOLACTONE 25MG TAB",
           "days_dispensed": null,
           "payment_method": "cheque",
           "refills_dispensed": 6,
           "price_dispensed": 0
       },
       {
           "invoice_number": "30967",
           "patient_id_cp": "7378",
           "patient_id_wc": "5315",
           "count_items": "1",
           "count_filled": 1,
           "count_nofill": null,
           "order_source": null,
           "order_stage_cp": "Entered",
           "order_stage_wc": null,
           "order_status": "Surescripts Fill",
           "invoice_doc_id": null,
           "order_address1": "1780 Corporate Dr",
           "order_address2": "Suite 100",
           "order_city": "Norcross",
           "order_state": "GA",
           "order_zip": "30093",
           "tracking_number": null,
           "order_date_added": "2020-03-27 10:39:27",
           "order_date_changed": "2020-03-27 10:39:27",
           "order_date_updated": "2020-03-27 14:40:31",
           "order_date_dispensed": null,
           "order_date_shipped": null,
           "order_date_returned": null,
           "payment_total_default": null,
           "payment_total_actual": null,
           "payment_fee_default": null,
           "payment_fee_actual": null,
           "payment_due_default": null,
           "payment_due_actual": null,
           "payment_date_autopay": null,
           "payment_method_actual": null,
           "coupon_lines": null,
           "order_note": null,
           "first_name": "FIRSTNAME",
           "last_name": "LASTNAME",
           "birth_date": "1985-03-10",
           "patient_note": "",
           "phone1": "1234567890",
           "phone2": null,
           "email": "april.britt@wellstar.org",
           "patient_autofill": "1",
           "pharmacy_name": "Wellstar Pharmacy Network",
           "pharmacy_npi": "1437458171",
           "pharmacy_fax": "7707939945",
           "pharmacy_phone": "7707939300",
           "pharmacy_address": "677 Church St Ne",
           "payment_card_type": null,
           "payment_card_last4": null,
           "payment_card_date_expired": null,
           "payment_method_default": "cheque",
           "payment_coupon": null,
           "tracking_coupon": null,
           "patient_address1": "1780 Corporate Dr",
           "patient_address2": "Suite 100",
           "patient_city": "Norcross",
           "patient_state": "GA",
           "patient_zip": "30093",
           "refills_used": "2.57",
           "patient_status": "1",
           "language": "EN",
           "allergies_none": null,
           "allergies_cephalosporins": null,
           "allergies_sulfa": null,
           "allergies_aspirin": null,
           "allergies_penicillin": null,
           "allergies_erythromycin": null,
           "allergies_codeine": null,
           "allergies_nsaids": null,
           "allergies_salicylates": null,
           "allergies_azithromycin": null,
           "allergies_amoxicillin": null,
           "allergies_tetracycline": null,
           "allergies_other": "Iodine",
           "medications_other": null,
           "patient_date_added": "2020-03-10 10:17:01",
           "patient_date_changed": "2020-03-10 00:00:00",
           "patient_date_updated": "2020-03-16 04:01:56",
           "drug_generic": "Torsemide 20mg",
           "drug_brand": null,
           "drug_name": "TORSEMIDE 20MG TAB",
           "sig_qty_per_day": "0.500",
           "max_gsn": "21408",
           "drug_gsns": ",21408,",
           "refills_total": "2.10",
           "rx_autofill": "1",
           "refill_date_first": "2020-03-12",
           "refill_date_last": "2020-03-12",
           "refill_date_next": "2020-06-10",
           "refill_date_manual": null,
           "refill_date_default": "2020-06-10",
           "best_rx_number": "6026806",
           "rx_numbers": ",6026806,",
           "rx_sources": "Refill",
           "rx_date_changed": "2020-03-12 11:38:08",
           "rx_date_expired": "2021-03-10",
           "rx_date_transferred": null,
           "rx_number": null,
           "rx_dispensed_id": null,
           "group": null,
           "stock_level_initial": null,
           "refills_dispensed_default": null,
           "refills_dispensed_actual": null,
           "days_dispensed_default": null,
           "days_dispensed_actual": null,
           "qty_dispensed_default": null,
           "qty_dispensed_actual": null,
           "price_dispensed_default": null,
           "price_dispensed_actual": null,
           "qty_pended_total": null,
           "qty_pended_repacks": null,
           "count_pended_total": null,
           "count_pended_repacks": null,
           "item_message_key": "NO ACTION NOT DUE",
           "item_message_text": "is not due until 2020-06-10 **",
           "item_type": null,
           "item_added_by": null,
           "item_date_added": null,
           "refill_target_date": null,
           "refill_target_days": null,
           "refill_target_rxs": null,
           "rx_gsn": null,
           "days_left": null,
           "refills_left": null,
           "refills_original": null,
           "qty_left": null,
           "qty_original": null,
           "sig_actual": null,
           "sig_initial": null,
           "sig_clean": null,
           "sig_qty": null,
           "sig_days": null,
           "sig_durations": null,
           "sig_qtys_per_time": null,
           "sig_frequencies": null,
           "sig_frequency_numerators": null,
           "sig_frequency_denominators": null,
           "rx_status": null,
           "rx_stage": null,
           "rx_source": null,
           "rx_transfer": null,
           "provider_npi": null,
           "provider_first_name": null,
           "provider_last_name": null,
           "provider_clinic": null,
           "provider_phone": null,
           "message_display": null,
           "stock_level": "HIGH SUPPLY",
           "price_per_month": "2.00",
           "drug_ordered": "1",
           "qty_repack": "135",
           "qty_inventory": "12149.0",
           "qty_entered": "9645.0",
           "qty_dispensed": 0,
           "stock_threshold": "2.4",
           "drug": "TORSEMIDE 20MG TAB",
           "days_dispensed": null,
           "payment_method": "cheque",
           "refills_dispensed": 2.1,
           "price_dispensed": 0
       }
   ]
